
local definitions = {
	{
		id = "dailyFunDabbler",
		titleKey = "achievements_definitions.dailyFunDabbler.title",
		descriptionKey = "achievements_definitions.dailyFunDabbler.description",
		icon = "dailyFunDabbler",
		goal = 1,
		stat = "dailyChallengesCompleted",
		category = "progress",
		categoryOrder = 1,
		order = 140,
	},
	{
		id = "comboSpark",
		titleKey = "achievements_definitions.comboSpark.title",
		descriptionKey = "achievements_definitions.comboSpark.description",
		icon = "comboSpark",
		goal = 3,
		stat = "bestComboStreak",
		category = "skill",
		categoryOrder = 2,
		order = 12,
	},
	{
		id = "comboSurge",
		titleKey = "achievements_definitions.comboSurge.title",
		descriptionKey = "achievements_definitions.comboSurge.description",
		icon = "comboSurge",
		goal = 6,
		stat = "bestComboStreak",
		category = "skill",
		categoryOrder = 2,
		order = 14,
	},
	{
		id = "rockCrusher",
		titleKey = "achievements_definitions.rockCrusher.title",
		descriptionKey = "achievements_definitions.rockCrusher.description",
		icon = "rockCrusher",
		goal = 25,
		stat = "shieldRockBreaks",
		category = "skill",
		categoryOrder = 2,
		order = 75,
	},
	{
		id = "sawAnnihilator",
		titleKey = "achievements_definitions.sawAnnihilator.title",
		descriptionKey = "achievements_definitions.sawAnnihilator.description",
		icon = "sawAnnihilator",
		goal = 25,
		stat = "shieldSawParries",
		category = "skill",
		categoryOrder = 2,
		order = 82,
	},
	{
		id = "dragonHunter",
		titleKey = "achievements_definitions.dragonHunter.title",
		descriptionKey = "achievements_definitions.dragonHunter.description",
		icon = "dragonHunter",
		goal = 1,
		stat = "totalDragonfruitEaten",
		category = "collection",
		categoryOrder = 3,
		order = 10,
	},
	{
		id = "dragonConnoisseur",
		titleKey = "achievements_definitions.dragonConnoisseur.title",
		descriptionKey = "achievements_definitions.dragonConnoisseur.description",
		icon = "dragonConnoisseur",
		goal = 5,
		stat = "totalDragonfruitEaten",
		category = "collection",
		categoryOrder = 3,
		order = 20,
	},
}

return definitions