local definitions = {
	{
		id = "AppleHoarder",
		TitleKey = "achievements_definitions.appleHoarder.title",
		DescriptionKey = "achievements_definitions.appleHoarder.description",
		icon = "fruit100",
		goal = 100,
		stat = "TotalApplesEaten",
		category = "progress",
		CategoryOrder = 1,
		order = 20,
	},
	{
		id = "AppleConqueror",
		TitleKey = "achievements_definitions.appleConqueror.title",
		DescriptionKey = "achievements_definitions.appleConqueror.description",
		icon = "fruit500",
		goal = 500,
		stat = "TotalApplesEaten",
		category = "progress",
		CategoryOrder = 1,
		order = 30,
	},
	{
		id = "AppleTycoon",
		TitleKey = "achievements_definitions.appleTycoon.title",
		DescriptionKey = "achievements_definitions.appleTycoon.description",
		icon = "fruit1000",
		goal = 1000,
		stat = "TotalApplesEaten",
		category = "progress",
		CategoryOrder = 1,
		order = 40,
	},
	{
		id = "AppleEternal",
		TitleKey = "achievements_definitions.appleEternal.title",
		DescriptionKey = "achievements_definitions.appleEternal.description",
		icon = "fruit2500",
		goal = 2500,
		stat = "TotalApplesEaten",
		category = "progress",
		CategoryOrder = 1,
		order = 50,
	},
	{
		id = "AppleInfinite",
		TitleKey = "achievements_definitions.appleInfinite.title",
		DescriptionKey = "achievements_definitions.appleInfinite.description",
		icon = "fruit5000",
		goal = 5000,
		stat = "TotalApplesEaten",
		category = "progress",
		CategoryOrder = 1,
		order = 55,
	},
	{
		id = "SeasonedRunner",
		TitleKey = "achievements_definitions.seasonedRunner.title",
		DescriptionKey = "achievements_definitions.seasonedRunner.description",
		icon = "Apple",
		goal = 20,
		stat = "SessionsPlayed",
		category = "progress",
		CategoryOrder = 1,
		order = 60,
	},
	{
		id = "MetaMilestone1",
		TitleKey = "achievements_definitions.metaMilestone1.title",
		DescriptionKey = "achievements_definitions.metaMilestone1.description",
		icon = "Apple",
		goal = 650,
		stat = "TotalMetaExperience",
		category = "progress",
		CategoryOrder = 1,
		order = 70,
	},
	{
		id = "MetaMilestone2",
		TitleKey = "achievements_definitions.metaMilestone2.title",
		DescriptionKey = "achievements_definitions.metaMilestone2.description",
		icon = "Apple",
		goal = 1300,
		stat = "TotalMetaExperience",
		category = "progress",
		CategoryOrder = 1,
		order = 80,
	},
	{
		id = "MetaMilestone3",
		TitleKey = "achievements_definitions.metaMilestone3.title",
		DescriptionKey = "achievements_definitions.metaMilestone3.description",
		icon = "Apple",
		goal = 2400,
		stat = "TotalMetaExperience",
		category = "progress",
		CategoryOrder = 1,
		order = 90,
	},
	{
		id = "MetaMilestone4",
		TitleKey = "achievements_definitions.metaMilestone4.title",
		DescriptionKey = "achievements_definitions.metaMilestone4.description",
		icon = "Apple",
		goal = 3800,
		stat = "TotalMetaExperience",
		category = "progress",
		CategoryOrder = 1,
		order = 100,
	},
	{
		id = "MetaMilestone5",
		TitleKey = "achievements_definitions.metaMilestone5.title",
		DescriptionKey = "achievements_definitions.metaMilestone5.description",
		icon = "Apple",
		goal = 5200,
		stat = "TotalMetaExperience",
		category = "progress",
		CategoryOrder = 1,
		order = 110,
	},
	{
		id = "MetaMilestone6",
		TitleKey = "achievements_definitions.metaMilestone6.title",
		DescriptionKey = "achievements_definitions.metaMilestone6.description",
		icon = "Apple",
		goal = 7800,
		stat = "TotalMetaExperience",
		category = "progress",
		CategoryOrder = 1,
		order = 120,
	},
	{
		id = "MetaMilestone7",
		TitleKey = "achievements_definitions.metaMilestone7.title",
		DescriptionKey = "achievements_definitions.metaMilestone7.description",
		icon = "Apple",
		goal = 10500,
		stat = "TotalMetaExperience",
		category = "progress",
		CategoryOrder = 1,
		order = 130,
	},
	{
		id = "DailyFunDabbler",
		TitleKey = "achievements_definitions.dailyFunDabbler.title",
		DescriptionKey = "achievements_definitions.dailyFunDabbler.description",
		icon = "Default",
		goal = 1,
		stat = "DailyChallengesCompleted",
		category = "progress",
		CategoryOrder = 1,
		order = 140,
	},
	{
		id = "DailyFunRegular",
		TitleKey = "achievements_definitions.dailyFunRegular.title",
		DescriptionKey = "achievements_definitions.dailyFunRegular.description",
		icon = "Default",
		goal = 10,
		stat = "DailyChallengesCompleted",
		category = "progress",
		CategoryOrder = 1,
		order = 150,
	},
	{
		id = "DailyFunChampion",
		TitleKey = "achievements_definitions.dailyFunChampion.title",
		DescriptionKey = "achievements_definitions.dailyFunChampion.description",
		icon = "Default",
		goal = 30,
		stat = "DailyChallengesCompleted",
		category = "progress",
		CategoryOrder = 1,
		order = 160,
	},
	{
		id = "FloorScout",
		TitleKey = "achievements_definitions.floorScout.title",
		DescriptionKey = "achievements_definitions.floorScout.description",
		icon = "Apple",
		goal = 3,
		stat = "DeepestFloorReached",
		category = "depth",
		CategoryOrder = 1.5,
		order = 10,
	},
	{
		id = "FloorDiver",
		TitleKey = "achievements_definitions.floorDiver.title",
		DescriptionKey = "achievements_definitions.floorDiver.description",
		icon = "Apple",
		goal = 6,
		stat = "DeepestFloorReached",
		category = "depth",
		CategoryOrder = 1.5,
		order = 20,
	},
	{
		id = "FloorAbyss",
		TitleKey = "achievements_definitions.floorAbyss.title",
		DescriptionKey = "achievements_definitions.floorAbyss.description",
		icon = "Apple",
		goal = 10,
		stat = "DeepestFloorReached",
		category = "depth",
		CategoryOrder = 1.5,
		order = 30,
	},
	{
		id = "FloorAscendant",
		TitleKey = "achievements_definitions.floorAscendant.title",
		DescriptionKey = "achievements_definitions.floorAscendant.description",
		icon = "Apple",
		goal = 14,
		stat = "DeepestFloorReached",
		category = "depth",
		CategoryOrder = 1.5,
		order = 40,
	},
	{
		id = "FloorVoyager",
		TitleKey = "achievements_definitions.floorVoyager.title",
		DescriptionKey = "achievements_definitions.floorVoyager.description",
		icon = "Apple",
		goal = 60,
		stat = "FloorsCleared",
		category = "depth",
		CategoryOrder = 1.5,
		order = 60,
	},
	{
		id = "FullBelly",
		TitleKey = "achievements_definitions.fullBelly.title",
		DescriptionKey = "achievements_definitions.fullBelly.description",
		icon = "Apple",
		goal = 50,
		category = "skill",
		CategoryOrder = 2,
		order = 10,
		ProgressFn = function(state)
			return state.snakeLength or 0
		end,
	},
	{
		id = "ComboSpark",
		TitleKey = "achievements_definitions.comboSpark.title",
		DescriptionKey = "achievements_definitions.comboSpark.description",
		icon = "Apple",
		goal = 3,
		stat = "BestComboStreak",
		category = "skill",
		CategoryOrder = 2,
		order = 12,
	},
	{
		id = "ComboSurge",
		TitleKey = "achievements_definitions.comboSurge.title",
		DescriptionKey = "achievements_definitions.comboSurge.description",
		icon = "Apple",
		goal = 6,
		stat = "BestComboStreak",
		category = "skill",
		CategoryOrder = 2,
		order = 14,
	},
	{
		id = "ComboInferno",
		TitleKey = "achievements_definitions.comboInferno.title",
		DescriptionKey = "achievements_definitions.comboInferno.description",
		icon = "Apple",
		goal = 10,
		stat = "BestComboStreak",
		category = "skill",
		CategoryOrder = 2,
		order = 16,
	},
	{
		id = "StraightLineSnacker",
		TitleKey = "achievements_definitions.straightLineSnacker.title",
		DescriptionKey = "achievements_definitions.straightLineSnacker.description",
		icon = "Apple",
		goal = 3,
		stat = "FruitWithoutTurning",
		category = "skill",
		CategoryOrder = 2,
		order = 18,
		hidden = true,
	},
	{
		id = "ShieldlessWonder",
		TitleKey = "achievements_definitions.shieldlessWonder.title",
		DescriptionKey = "achievements_definitions.shieldlessWonder.description",
		icon = "Apple",
		goal = 1,
		category = "skill",
		CategoryOrder = 2,
		order = 19,
		hidden = true,
		ProgressFn = function(state)
			if (state.runFloorsCleared or 0) >= 3 and (state.runCrashShieldsSaved or 0) == 0 then
				return 1
			end
			return 0
		end,
		condition = function(state)
			return (state.runFloorsCleared or 0) >= 3 and (state.runCrashShieldsSaved or 0) == 0
		end,
	},
	{
		id = "ScoreChaser",
		TitleKey = "achievements_definitions.scoreChaser.title",
		DescriptionKey = "achievements_definitions.scoreChaser.description",
		icon = "Apple",
		goal = 250,
		stat = "BestScore",
		category = "skill",
		CategoryOrder = 2,
		order = 20,
	},
	{
		id = "FruitFiesta",
		TitleKey = "achievements_definitions.fruitFiesta.title",
		DescriptionKey = "achievements_definitions.fruitFiesta.description",
		icon = "Apple",
		goal = 25,
		stat = "RunApplesEaten",
		category = "skill",
		CategoryOrder = 2,
		order = 30,
	},
	{
		id = "FloorSprinter",
		TitleKey = "achievements_definitions.floorSprinter.title",
		DescriptionKey = "achievements_definitions.floorSprinter.description",
		icon = "Apple",
		goal = 3,
		stat = "RunFloorsCleared",
		category = "skill",
		CategoryOrder = 2,
		order = 40,
	},
	{
		id = "ScoreLegend",
		TitleKey = "achievements_definitions.scoreLegend.title",
		DescriptionKey = "achievements_definitions.scoreLegend.description",
		icon = "Apple",
		goal = 500,
		stat = "BestScore",
		category = "skill",
		CategoryOrder = 2,
		order = 50,
	},
	{
		id = "DragonComboFusion",
		TitleKey = "achievements_definitions.dragonComboFusion.title",
		DescriptionKey = "achievements_definitions.dragonComboFusion.description",
		icon = "Apple",
		goal = 1,
		category = "skill",
		CategoryOrder = 2,
		order = 55,
		hidden = true,
		ProgressFn = function(state)
			if (state.runDragonfruitEaten or 0) > 0 and (state.runBestComboStreak or 0) >= 8 then
				return 1
			end
			return 0
		end,
		condition = function(state)
			return (state.runDragonfruitEaten or 0) > 0 and (state.runBestComboStreak or 0) >= 8
		end,
	},
	{
		id = "WallRicochet",
		TitleKey = "achievements_definitions.wallRicochet.title",
		DescriptionKey = "achievements_definitions.wallRicochet.description",
		icon = "Apple",
		goal = 1,
		stat = "ShieldWallBounces",
		category = "skill",
		CategoryOrder = 2,
		order = 60,
	},
	{
		id = "RockShatter",
		TitleKey = "achievements_definitions.rockShatter.title",
		DescriptionKey = "achievements_definitions.rockShatter.description",
		icon = "Apple",
		goal = 1,
		stat = "ShieldRockBreaks",
		category = "skill",
		CategoryOrder = 2,
		order = 70,
	},
	{
		id = "RockCrusher",
		TitleKey = "achievements_definitions.rockCrusher.title",
		DescriptionKey = "achievements_definitions.rockCrusher.description",
		icon = "Apple",
		goal = 25,
		stat = "ShieldRockBreaks",
		category = "skill",
		CategoryOrder = 2,
		order = 75,
	},
	{
		id = "SawParry",
		TitleKey = "achievements_definitions.sawParry.title",
		DescriptionKey = "achievements_definitions.sawParry.description",
		icon = "Apple",
		goal = 1,
		stat = "ShieldSawParries",
		category = "skill",
		CategoryOrder = 2,
		order = 80,
	},
	{
		id = "SawAnnihilator",
		TitleKey = "achievements_definitions.sawAnnihilator.title",
		DescriptionKey = "achievements_definitions.sawAnnihilator.description",
		icon = "Apple",
		goal = 25,
		stat = "ShieldSawParries",
		category = "skill",
		CategoryOrder = 2,
		order = 82,
	},
	{
		id = "ShieldTriad",
		TitleKey = "achievements_definitions.shieldTriad.title",
		DescriptionKey = "achievements_definitions.shieldTriad.description",
		icon = "Apple",
		goal = 3,
		category = "skill",
		CategoryOrder = 2,
		order = 85,
		ProgressFn = function(state)
			local count = 0
			local keys = {
				"RunShieldWallBounces",
				"RunShieldRockBreaks",
				"RunShieldSawParries",
			}

			for _, key in ipairs(keys) do
				if (state[key] or 0) > 0 then
					count = count + 1
				end
			end

			return count
		end,
		condition = function(state)
			local progress = 0
			local keys = {
				"RunShieldWallBounces",
				"RunShieldRockBreaks",
				"RunShieldSawParries",
			}

			for _, key in ipairs(keys) do
				if (state[key] or 0) > 0 then
					progress = progress + 1
				end
			end

			return progress >= 3
		end,
	},
	{
		id = "DragonHunter",
		TitleKey = "achievements_definitions.dragonHunter.title",
		DescriptionKey = "achievements_definitions.dragonHunter.description",
		icon = "Apple",
		goal = 1,
		stat = "TotalDragonfruitEaten",
		category = "collection",
		CategoryOrder = 3,
		order = 10,
	},
	{
		id = "DragonConnoisseur",
		TitleKey = "achievements_definitions.dragonConnoisseur.title",
		DescriptionKey = "achievements_definitions.dragonConnoisseur.description",
		icon = "Apple",
		goal = 10,
		stat = "TotalDragonfruitEaten",
		category = "collection",
		CategoryOrder = 3,
		order = 20,
	},
}

return definitions
